-- =========================================================
-- VOX MARKETPLACE — SUPABASE
-- Ejecuta este script en Supabase > SQL Editor
-- =========================================================

create extension if not exists pgcrypto;

-- ---------- ADMINISTRADORES ----------
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text not null default 'admin',
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

-- Función segura para comprobar si el usuario es administrador.
create or replace function public.is_admin(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = uid
  );
$$;

revoke all on function public.is_admin(uuid) from public;
grant execute on function public.is_admin(uuid) to anon, authenticated;

-- ---------- PRODUCTOS ----------
create table if not exists public.products (
  id uuid primary key,
  name text not null,
  price numeric(12,2) not null default 0,
  stock integer not null default 0,
  category text,
  description text,
  sizes jsonb not null default '[]'::jsonb,
  colors jsonb not null default '[]'::jsonb,
  image_urls jsonb not null default '[]'::jsonb,
  cover_index integer not null default 0,
  active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;

drop policy if exists "Public can see active products" on public.products;
create policy "Public can see active products"
on public.products for select
to anon, authenticated
using (active = true or public.is_admin(auth.uid()));

drop policy if exists "Admins can insert products" on public.products;
create policy "Admins can insert products"
on public.products for insert
to authenticated
with check (public.is_admin(auth.uid()));

drop policy if exists "Admins can update products" on public.products;
create policy "Admins can update products"
on public.products for update
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products"
on public.products for delete
to authenticated
using (public.is_admin(auth.uid()));

-- ---------- ANALÍTICA ----------
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  product_id uuid references public.products(id) on delete set null,
  visitor_id text,
  page_path text,
  referrer text,
  source text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_idx
  on public.analytics_events(created_at desc);

create index if not exists analytics_events_event_idx
  on public.analytics_events(event_name);

create index if not exists analytics_events_product_idx
  on public.analytics_events(product_id);

alter table public.analytics_events enable row level security;

drop policy if exists "Public can send analytics" on public.analytics_events;
create policy "Public can send analytics"
on public.analytics_events for insert
to anon, authenticated
with check (true);

drop policy if exists "Admins can read analytics" on public.analytics_events;
create policy "Admins can read analytics"
on public.analytics_events for select
to authenticated
using (public.is_admin(auth.uid()));

-- ---------- STORAGE ----------
-- Crea el bucket para las imágenes de productos.
insert into storage.buckets (id, name, public)
values ('products', 'products', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can view product images" on storage.objects;
create policy "Public can view product images"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'products');

drop policy if exists "Admins can upload product images" on storage.objects;
create policy "Admins can upload product images"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'products'
  and public.is_admin(auth.uid())
);

drop policy if exists "Admins can update product images" on storage.objects;
create policy "Admins can update product images"
on storage.objects for update
to authenticated
using (
  bucket_id = 'products'
  and public.is_admin(auth.uid())
)
with check (
  bucket_id = 'products'
  and public.is_admin(auth.uid())
);

drop policy if exists "Admins can delete product images" on storage.objects;
create policy "Admins can delete product images"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'products'
  and public.is_admin(auth.uid())
);

-- =========================================================
-- PASO FINAL: después de crear el usuario administrador en
-- Supabase Authentication > Users, ejecuta esta línea
-- cambiando el correo por el del administrador.
--
-- insert into public.admin_users(user_id, email)
-- select id, email
-- from auth.users
-- where email = 'TU_CORREO_ADMIN@ejemplo.com'
-- on conflict (user_id) do nothing;
--
-- IMPORTANTE:
-- La contraseña se administra desde Supabase Authentication.
-- Nunca la guardes en este archivo.
-- =========================================================
